framework:
    messenger:
        default_bus: messenger.bus.default

        # define your transports
        transports:
            async_notifications:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    max_retries: 0 # first try only
            failed_notifications:
                dsn: "doctrine://default?queue_name=failed_notifications"
                retry_strategy:
                    max_retries: 5 # 5 retries
                    delay: 10000 # 10 sec
                    multiplier: 2
                    max_delay: 60000 # 1 m

        routing:
            'App\Messenger\NotificationMessage': async_notifications

        failure_transport: failed_notifications
