# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\NotificationService:
        arguments:
            $providers: !tagged_iterator app.notifier.provider
            $logger: "@logger"
            $notifierLogger: "@monolog.logger.notification"

    App\Service\Provider\SesNotifier:
        arguments:
            $from: "%env(EMAIL_FROM)%"
        tags:
            - { name: "app.notifier.provider" }

    Twilio\Rest\Client:
        arguments:
            - "%env(TWILIO_SID)%"
            - "%env(TWILIO_AUTH_TOKEN)%"
        public: false

    App\Service\Provider\TwilioNotifier:
        arguments:
            $twilioClient: '@Twilio\Rest\Client'
            $from: "%env(TWILIO_FROM)%"
            $logger: "@logger"
        tags:
            - { name: "app.notifier.provider", priority: 100 }

    Aws\Sns\SnsClient:
        arguments:
            - version: "2010-03-31"
              region: "%env(AWS_SNS_REGION)%"
              credentials:
                  key: "%env(AWS_SNS_KEY)%"
                  secret: "%env(AWS_SNS_SECRET)%"
        public: false

    App\Service\Provider\SnsNotifier:
        arguments:
            $snsClient: '@Aws\Sns\SnsClient'
            $logger: "@logger"
        tags:
            - { name: "app.notifier.provider", priority: 80 }
